### ISSUE TITLE
Automatically Add Build Artifacts to Release

### ISSUE THREAD

**Issue by kylerobots** [kylerobots/example-python-package#21]
A workflow can be set up that allows the `tar.gz` and `.whl` files made in the build step to be uploaded to the same release. Something like this (Copilot wrote this code):

```
name: Build and Upload Python Package

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Upload distribution to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/your-package-name-1.0.0.tar.gz
        asset_name: your-package-name-1.0.0.tar.gz
        asset_content_type: application/gzip
```
